/**
 * Example data — four-plus months of realistic history, generated by replaying
 * the real action functions with backdated timestamps, so every split receipt
 * is exactly what the engine would have produced. Wipe with one click in Rules.
 */

import type { AppData } from "./types";
import { emptyData } from "./types";
import {
  addAccount,
  addAsset,
  addDebt,
  addGoal,
  addReceivable,
  adjust,
  lendMoney,
  logIncome,
  logSpend,
  payDebt,
  payProvision,
  setAssetAccount,
  setPoolAccount,
  takeWeeklyAllowance,
  withdrawAccessible,
} from "./engine/actions";
import { deriveState } from "./engine/replay";
import { addDays, addMonths, startOfWeek, toISODate } from "./lib/util";

export function buildSeedData(now: Date = new Date()): AppData {
  const data = emptyData();
  data.settings.livingExpensesMonthly = 2400;
  data.settings.regularWeekly = 200;

  const start = addDays(now, -130);
  const at = (daysFromStart: number, hour = 10): Date => {
    const d = addDays(start, daysFromStart);
    d.setHours(hour, 15, 0, 0);
    return d;
  };

  /* Opening: move existing cash into the reserve, on the record.
   * Sized so the deep reserve sits comfortably above the Floor, leaving room
   * to demonstrate lending from it. */
  adjust(
    data,
    "reserve",
    10000,
    "Opening balance — moved existing savings into Regular",
    undefined,
    at(0, 9)
  );

  /* Goals. Land is the top priority — it receives surplus sweeps. */
  addGoal(
    data,
    {
      kind: "accumulating",
      name: "Land",
      target: 30000,
      targetDate: toISODate(addMonths(now, 20)),
    },
    at(0)
  );
  addGoal(
    data,
    {
      kind: "accumulating",
      name: "Index fund lump",
      target: 6000,
      targetDate: toISODate(addMonths(now, 6)),
    },
    at(0)
  );
  addGoal(
    data,
    {
      kind: "provision",
      name: "Rent",
      target: 1150,
      targetDate: toISODate(addDays(start, 30)),
      recurrence: "monthly",
    },
    at(0)
  );
  addGoal(
    data,
    {
      kind: "provision",
      name: "Car insurance",
      target: 420,
      targetDate: toISODate(addMonths(now, 1)),
      recurrence: "quarterly",
    },
    at(0)
  );

  /* Outside assets. */
  const corolla = addAsset(data, { name: "2018 Corolla", category: "vehicle", value: 11500 }, at(1));
  const hysa = addAsset(data, { name: "High-yield savings", category: "savings", value: 4200 }, at(1));
  const btc = addAsset(data, { name: "Bitcoin", category: "crypto", value: 2800 }, at(1));

  /* Accounts — where the money lives — with the pools and assets assigned. */
  const ally = addAccount(data, { name: "Ally Savings", type: "savings", note: "…4021" }, at(1));
  const chase = addAccount(data, { name: "Chase Checking", type: "checking", note: "…8830" }, at(1));
  const wealthfront = addAccount(data, { name: "Wealthfront", type: "brokerage" }, at(1));
  const coinbase = addAccount(data, { name: "Coinbase", type: "crypto" }, at(1));
  setPoolAccount(data, "reserve", ally.id);
  setPoolAccount(data, "allowance", chase.id);
  setPoolAccount(data, "goals", wealthfront.id);
  setPoolAccount(data, "provisions", chase.id);
  setAssetAccount(data, hysa.id, ally.id);
  setAssetAccount(data, btc.id, coinbase.id);
  void corolla; // the car stays unassigned (property, not held at an institution)

  /* Income: multiple sources, irregular amounts — the app's whole premise. */
  const incomes: Array<[number, number, string]> = [
    [2, 1850, "Design retainer"],
    [11, 640, "Freelance"],
    [19, 1400, "Design retainer"],
    [26, 320, "Course sales"],
    [33, 2100, "Design retainer"],
    [41, 780, "Freelance"],
    [49, 1850, "Design retainer"],
    [55, 260, "Course sales"],
    [63, 1500, "Design retainer"],
    [71, 950, "Freelance"],
    [78, 2200, "Design retainer"],
    [86, 410, "Course sales"],
    [93, 1850, "Design retainer"],
    [101, 700, "Freelance"],
    [108, 1600, "Design retainer"],
    [116, 2350, "Design retainer"],
    [123, 520, "Course sales"],
    [128, 1400, "Freelance"],
  ];

  /* Rent comes due roughly every 30 days; pay it when the day arrives. */
  const payDueProvisions = (day: number) => {
    const nowAt = at(day, 12);
    const d = deriveState(data, nowAt);
    for (const g of data.goals) {
      if (
        g.status === "active" &&
        g.kind === "provision" &&
        g.recurrence === "monthly" &&
        new Date(g.targetDate).getTime() <= nowAt.getTime() &&
        (d.goalBalances[g.id] ?? 0) > 0
      ) {
        payProvision(data, g.id, nowAt);
      }
    }
  };

  for (const [day, amount, source] of incomes) {
    logIncome(data, amount, source, at(day));
    payDueProvisions(day);
  }

  /* One "life happens" moment through the accessible door. */
  withdrawAccessible(data, 180, "Health", "Phone screen repair", at(75, 16));

  /* Receivables — money owed to me, at varying confidence.
   * "Dayo" is expected in the past so the Console's calm overdue line shows. */
  addReceivable(
    data,
    {
      person: "Dayo",
      amount: 500,
      expectedDate: toISODate(addDays(now, -6)),
      note: "Covered his flight, said he'd send it back",
      confidence: "hopeful",
    },
    at(40)
  );
  addReceivable(
    data,
    {
      person: "Sister",
      amount: 1200,
      expectedDate: toISODate(addMonths(now, 2)),
      note: "Helped with her deposit",
      confidence: "likely",
    },
    at(60)
  );
  /* A small deliberate loan from the accessible reserve (immediate, no cooldown). */
  lendMoney(
    data,
    {
      person: "Tobi",
      amount: 300,
      layer: "accessible",
      confidence: "certain",
      reason: "Bridge until his payday",
    },
    at(112, 15)
  );

  /* A described withdrawal from the accessible reserve. */
  withdrawAccessible(data, 150, "Family", "Monthly to sister", at(121, 11));

  /* A debt owed, with a due date, partly paid down. */
  const laptop = addDebt(
    data,
    {
      name: "Laptop financing",
      amount: 1200,
      dueDate: toISODate(addMonths(now, 3)),
      note: "0% plan, 4 payments left",
    },
    at(90)
  );
  payDebt(data, laptop.id, 300, "accessible", at(118, 14));

  /* Weekly allowance taken for the two most recent past weeks — seeds the
   * tracker so recent weeks read as taken. */
  const thisMonday = startOfWeek(now);
  takeWeeklyAllowance(data, toISODate(addDays(thisMonday, -7)), addDays(now, -4));
  takeWeeklyAllowance(data, toISODate(addDays(thisMonday, -14)), addDays(now, -11));

  return data;
}

