/**
 * Example data — four-plus months of realistic history, generated by replaying
 * the real action functions with backdated timestamps, so every split receipt
 * is exactly what the engine would have produced. Wipe with one click in Rules.
 */

import type { AppData } from "./types";
import { emptyData } from "./types";
import {
  addAsset,
  addGoal,
  adjust,
  logIncome,
  logSpend,
  payProvision,
  withdrawAccessible,
} from "./engine/actions";
import { deriveState } from "./engine/replay";
import { addDays, addMonths, toISODate } from "./lib/util";

export function buildSeedData(now: Date = new Date()): AppData {
  const data = emptyData();
  data.settings.livingExpensesMonthly = 2400;
  data.settings.regularWeekly = 200;

  const start = addDays(now, -130);
  const at = (daysFromStart: number, hour = 10): Date => {
    const d = addDays(start, daysFromStart);
    d.setHours(hour, 15, 0, 0);
    return d;
  };

  /* Opening: move existing cash into the reserve, on the record. */
  adjust(
    data,
    "reserve",
    6000,
    "Opening balance — moved existing savings into Regular",
    undefined,
    at(0, 9)
  );

  /* Goals. Land is the top priority — it receives surplus sweeps. */
  addGoal(
    data,
    {
      kind: "accumulating",
      name: "Land",
      target: 30000,
      targetDate: toISODate(addMonths(now, 20)),
    },
    at(0)
  );
  addGoal(
    data,
    {
      kind: "accumulating",
      name: "Index fund lump",
      target: 6000,
      targetDate: toISODate(addMonths(now, 6)),
    },
    at(0)
  );
  addGoal(
    data,
    {
      kind: "provision",
      name: "Rent",
      target: 1150,
      targetDate: toISODate(addDays(start, 30)),
      recurrence: "monthly",
    },
    at(0)
  );
  addGoal(
    data,
    {
      kind: "provision",
      name: "Car insurance",
      target: 420,
      targetDate: toISODate(addMonths(now, 1)),
      recurrence: "quarterly",
    },
    at(0)
  );

  /* Outside assets. */
  addAsset(data, { name: "2018 Corolla", category: "vehicle", value: 11500 }, at(1));
  addAsset(data, { name: "High-yield savings", category: "savings", value: 4200 }, at(1));
  addAsset(data, { name: "Bitcoin", category: "crypto", value: 2800 }, at(1));

  /* Income: multiple sources, irregular amounts — the app's whole premise. */
  const incomes: Array<[number, number, string]> = [
    [2, 1850, "Design retainer"],
    [11, 640, "Freelance"],
    [19, 1400, "Design retainer"],
    [26, 320, "Course sales"],
    [33, 2100, "Design retainer"],
    [41, 780, "Freelance"],
    [49, 1850, "Design retainer"],
    [55, 260, "Course sales"],
    [63, 1500, "Design retainer"],
    [71, 950, "Freelance"],
    [78, 2200, "Design retainer"],
    [86, 410, "Course sales"],
    [93, 1850, "Design retainer"],
    [101, 700, "Freelance"],
    [108, 1600, "Design retainer"],
    [116, 2350, "Design retainer"],
    [123, 520, "Course sales"],
    [128, 1400, "Freelance"],
  ];

  /* Rent comes due roughly every 30 days; pay it when the day arrives. */
  const payDueProvisions = (day: number) => {
    const nowAt = at(day, 12);
    const d = deriveState(data, nowAt);
    for (const g of data.goals) {
      if (
        g.status === "active" &&
        g.kind === "provision" &&
        g.recurrence === "monthly" &&
        new Date(g.targetDate).getTime() <= nowAt.getTime() &&
        (d.goalBalances[g.id] ?? 0) > 0
      ) {
        payProvision(data, g.id, nowAt);
      }
    }
  };

  for (const [day, amount, source] of incomes) {
    logIncome(data, amount, source, at(day));
    payDueProvisions(day);
  }

  /* One "life happens" moment through the accessible door. */
  withdrawAccessible(data, 180, "Phone screen repair", at(75, 16));

  /* A little spend-game activity this week (optional, never homework). */
  const daysIn = 130;
  logSpend(data, 42.5, at(daysIn - 2, 13));
  logSpend(data, 18, at(daysIn - 1, 19));
  logSpend(data, 26.75, at(daysIn, 9));

  return data;
}

